GET http://localhost:8080/api/companies

############################################
POST http://localhost:8080/api/companies
Content-Type: application/json

{
  "name": "Google",
  "website": "https://www.google.com/",
  "location": "Kristianstad"
}

#########################################