GET http://localhost:8080/api/jobs

############################################
POST http://localhost:8080/api/jobs
Content-Type: application/json

{
  "title": "Software Engineer",
  "company": "Acme Inc",
  "description": "Java backend role",
  "status": "Applied",
  "appliedDate": "2026-05-29"
}

############################################
GET http://localhost:8080/api/jobs/1

{
  "id": 1
}

############################################
PUT http://localhost:8080/api/jobs/2
Content-Type: application/json

{
    "title": "poopy"
}