spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvsearch
    username: cvsearch
    password: cvsearch
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.apache.fontbox: ERROR

server:
  port: 8080



ollama:
  base-url: http://localhost:11434
  model: llama3.2
